# Generated by Django 4.0.3 on 2022-03-29 01:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmueblesListApp', '0003_inmueble_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmueblesList', to='inmueblesListApp.empresa'),
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('texto', models.CharField(max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now_add=True)),
                ('inmuebles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='inmueblesListApp.inmueble')),
            ],
        ),
    ]
