# Generated by Django 4.0.3 on 2022-05-25 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inmueblesListApp', '0004_alter_inmueble_empresa_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='Comentarios_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
