# Generated by Django 4.0.1 on 2022-07-27 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmueblesListApp', '0005_comentarios_comentarios_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=55)),
                ('descripcion', models.CharField(max_length=500)),
                ('imagen', models.CharField(max_length=900)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmueblesList', to='inmueblesListApp.empresa')),
            ],
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='inmuebles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='inmueblesListApp.edificacion'),
        ),
        migrations.DeleteModel(
            name='Inmueble',
        ),
    ]
