# Generated by Django 4.0.1 on 2022-07-28 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmueblesListApp', '0007_alter_edificacion_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificacion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EdificacionList', to='inmueblesListApp.empresa'),
        ),
    ]
